export const getRetailers = (basePrice) => [
  {
    id: "amazon-ae",
    name: "Amazon.ae",
    logo: "📦",
    price: Math.round(basePrice * 0.95),
    sellerType: "marketplace",
    badge: "Prime",
    badgeColor: "bg-primary",
    freeShipping: true,
    days: "1-2",
  },
  {
    id: "noon",
    name: "Noon",
    logo: "🛒",
    price: Math.round(basePrice * 0.98),
    sellerType: "marketplace",
    badge: "Express",
    badgeColor: "bg-secondary",
    freeShipping: false,
    days: "1-3",
  },
  {
    id: "sharaf-dg",
    name: "Sharaf DG",
    logo: "🏪",
    price: basePrice,
    sellerType: "official",
    badge: "Official",
    badgeColor: "bg-secondary",
    freeShipping: true,
    days: "1-3",
  },
  {
    id: "jumbo",
    name: "Jumbo Electronics",
    logo: "🏬",
    price: Math.round(basePrice * 1.02),
    sellerType: "official",
    badge: "Official",
    badgeColor: "bg-secondary",
    freeShipping: false,
    days: "2-4",
  },
  {
    id: "virgin",
    name: "Virgin Megastore",
    logo: "🎵",
    price: Math.round(basePrice * 1.05),
    sellerType: "official",
    badge: null,
    freeShipping: true,
    days: "2-5",
  },
];
